# Generated by Django 3.1 on 2020-08-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
